spring:
  cache:
    type: redis
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    hikari:
      maximum-pool-size: 3
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Explicit dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
      password: temppass
      timeout: 2000
hashids:
  salt: Lzdk8t9KJ3kN9

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html


