spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    hikari:
      maximum-pool-size: 3
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Explicit dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

hashids:
  salt: Lzdk8t9KJ3kN9

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html


