-- V1__initial_schema.sql

CREATE TABLE IF NOT EXISTS urls
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL UNIQUE
);

-- Optionally, you can add an index on the URL column if you're expecting frequent searches
CREATE INDEX IF NOT EXISTS idx_urls_url ON urls(url);
